
version: '3'
services:
  api:
    container_name: api
    build: .
    command: /bin/bash docker_start.sh
    volumes:
      - .:/my_app
    ports:
      - "4000:4000"
    links:
      - database
  database:
    container_name: database
    image: mariadb:10.2.15
    restart: always
    volumes:
      - "./volumes/datadir:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_app_dev
      MYSQL_USER: root
    ports:
      - "3306:3306"
